# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o 未命名2.o
LINKOBJ  = main.o 未命名2.o
LIBS     = -L"D:/software/devc++/Dev-Cpp/MinGW64/lib" -L"D:/software/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -g3
INCS     = -I"D:/software/devc++/Dev-Cpp/MinGW64/include" -I"D:/software/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/software/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/software/devc++/Dev-Cpp/MinGW64/include" -I"D:/software/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/software/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/software/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"D:/edage_download/库/ege24.04_all/ege24.04" -I"D:/software/devc++/Dev-Cpp/eigen-3.4.0"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c++11
CFLAGS   = $(INCS) -g3 -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

未命名2.o: 未命名2.cpp
	$(CPP) -c 未命名2.cpp -o 未命名2.o $(CXXFLAGS)
